StudentList/config/routes.rb
Rails.application.routes.draw do
  get 'info/personal'

  resources :students
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  # Serve websocket cable requests in-process
  # mount ActionCable.server => '/cable'
  root 'students#index'
end

StudentList/app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

StudentList/app/models/student.rb
class Student < ApplicationRecord
end

StudentList/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

StudentList/app/controllers/info_controller.rb
class InfoController < ApplicationController
  def personal
  end
end

StudentList/app/controllers/students_controller.rb
class StudentsController < ApplicationController
  before_action :set_student, only: [:show, :edit, :update, :destroy]

  http_basic_authenticate_with name: "admin", password: "admin", except: :index
  # GET /students
  # GET /students.json
  def index
    #@students = Student.all
    @student = Student.paginate(:page => params[:page], :per_page => 10)
  end

  # GET /students/1
  # GET /students/1.json
  def show
  end

  # GET /students/new
  def new
    @student = Student.new
  end

  # GET /students/1/edit
  def edit
  end

  # POST /students
  # POST /students.json
  def create
    @student = Student.new(student_params)

    respond_to do |format|
      if @student.save
        format.html { redirect_to @student, notice: 'Student was successfully created.' }
        format.json { render :show, status: :created, location: @student }
      else
        format.html { render :new }
        format.json { render json: @student.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /students/1
  # PATCH/PUT /students/1.json
  def update
    respond_to do |format|
      if @student.update(student_params)
        format.html { redirect_to @student, notice: 'Student was successfully updated.' }
        format.json { render :show, status: :ok, location: @student }
      else
        format.html { render :edit }
        format.json { render json: @student.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /students/1
  # DELETE /students/1.json
  def destroy
    @student.destroy
    respond_to do |format|
      format.html { redirect_to students_url, notice: 'Student was successfully deleted.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_student
      @student = Student.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def student_params
      params.require(:student).permit(:FirstName, :LastName, :Index)
    end
end

StudentList/app/helpers/application_helper.rb
module ApplicationHelper
end

StudentList/app/helpers/info_helper.rb
module InfoHelper
end

StudentList/app/helpers/students_helper.rb
module StudentsHelper
end

StudentList/app/views/info/personal.html.erb
<h1>About me</h1>
<p>My name is Mateusz. I'm IT student and it's my first rails app.</p>

StudentList/app/views/layouts/_header.html.erb
<header class="navbar navbar-fixed-top navbar-inverse">
  <div class="container">
    <nav>
      <ul class="nav navbar-nav navbar-right">
        <li><%= link_to "Home",  '/' %></li>
        <li><%= link_to "Personal info",  '/info/personal' %></li>
      </ul>
    </nav>
  </div>
</header>

StudentList/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>StudentList</title>
    <%= csrf_meta_tags %>
    <%= action_cable_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track' => 'reload' %>
  </head>

  <body>
    <%= render 'layouts/header' %>
    <div class="container">
      <%= yield %>
    </div>
  </body>
</html>

StudentList/app/views/students/_form.html.erb
<%= form_for @student, html: { class: 'form-horizontal' } do |f| %>
  <div class="form-group">
    <%= f.label :FirstName, class: 'control-label col-md-2' %>
    <div class="col-md-10">
      <%= f.text_field :FirstName, class: 'text_field form-control' %>
    </div>
  </div>
  <div class="form-group">
    <%= f.label :LastName, class: 'control-label col-md-2' %>
    <div class="col-md-10">
      <%= f.text_field :LastName, class: 'text_field form-control' %>
    </div>
  </div>
  <div class="form-group">
    <%= f.label :Index, class: 'control-label col-md-2' %>
    <div class="col-md-10">
      <%= f.text_field :Index, class: 'text_field form-control' %>
    </div>
  </div>

  <div class="form-group">
    <div class='col-md-offset-2 col-md-10'>
      <%= f.submit nil, class: 'btn btn-primary' %>
      <%= link_to t('.cancel', default: t("helpers.links.cancel")),
                  students_path, class: 'btn btn-default' %>
    </div>
  </div>
<% end %>

StudentList/app/views/students/edit.html.erb
<%- model_class = Student -%>
<div class="page-header">
  <h1><%=t '.title', default: [:'helpers.titles.edit', 'Edit %{model}'], model: model_class.model_name.human.titleize %></h1>
</div>
<%= render partial: 'form' %>

StudentList/app/views/students/index.html.erb
<%- model_class = Student -%>
<%= will_paginate @student %>
<div class="page-header">
  <h1><%=t '.title', default: model_class.model_name.human.pluralize.titleize %></h1>
</div>
<table class="table table-striped">
  <thead>
    <tr>
      <th><%= model_class.human_attribute_name(:id) %></th>
      <th><%= model_class.human_attribute_name(:FirstName) %></th>
      <th><%= model_class.human_attribute_name(:LastName) %></th>
      <th><%= model_class.human_attribute_name(:Index) %></th>
      <th><%= model_class.human_attribute_name(:created_at) %></th>
      <th><%=t '.actions', default: t("helpers.actions") %></th>
    </tr>
  </thead>
  <tbody>
    <% @student.each do |student| %>
      <tr>
        <td><%= student.id %></td>
          <td><%= student.FirstName %></td>
          <td><%= student.LastName %></td>
          <td><%= student.Index %></td>
        <td><%=l student.created_at, format: :long %></td>
        <td>
          <%= link_to student_path(student), class: 'btn btn-xs', title: "#{ t('.show', default: t('helpers.links.show')) }" do %>
            <%= glyph 'info-sign' %>
          <%- end -%>
          <%= link_to edit_student_path(student), class: 'btn btn-xs', title: "#{ t('.edit', default: t('helpers.links.edit')) }" do %>
            <%= glyph 'pencil' %>
          <%- end -%>
          <%= link_to student_path(student), method: :delete, data: { confirm: t('.confirm', default: t("helpers.links.confirm", default: 'Are you sure?')) }, class: 'btn btn-xs', title: "#{ t('.destroy', default: t('helpers.links.destroy')) }" do %>
            <%= glyph 'remove' %>
          <%- end -%>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

<%= link_to t('.new', default: t("helpers.links.new")),
            new_student_path,
            class: 'btn btn-primary' %>

StudentList/app/views/students/new.html.erb
<%- model_class = Student -%>
<div class="page-header">
  <h1><%=t '.title', default: [:'helpers.titles.new', 'New %{model}'], model: model_class.model_name.human.titleize %></h1>
</div>
<%= render partial: 'form' %>

StudentList/app/views/students/show.html.erb
<%- model_class = Student -%>
<div class="page-header">
  <h1><%=t '.title', default: model_class.model_name.human.titleize %></h1>
</div>

<div class="fieldset">
  <dl>
      <dt class="label label-default"><%= model_class.human_attribute_name(:FirstName) %></dt>
      <dd><pre class="prettyprint"><%= @student.FirstName %></pre></dd>
      <dt class="label label-default"><%= model_class.human_attribute_name(:LastName) %></dt>
      <dd><pre class="prettyprint"><%= @student.LastName %></pre></dd>
      <dt class="label label-default"><%= model_class.human_attribute_name(:Index) %></dt>
      <dd><pre class="prettyprint"><%= @student.Index %></pre></dd>
  </dl>
</div>

<div class="form-group">
  <%= link_to t('.back', default: t("helpers.links.back")),
              students_path, class: 'btn btn-default'  %>
  <%= link_to t('.edit', default: t("helpers.links.edit")),
              edit_student_path(@student), class: 'btn btn-default' %>
  <%= link_to t('.destroy', default: t("helpers.links.destroy")),
              student_path(@student),
              method: 'delete',
              data: { confirm: t('.confirm', default: t("helpers.links.confirm", default: 'Are you sure?')) },
              class: 'btn btn-danger' %>
</div>